### ISSUE TITLE
partial error 404 theming

### ISSUE THREAD

**Issue by isabelroses** [alaidriel/ctp-nixos-search#4]
This is the [link](https://search.nixos.org/flakes?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=hyrpland) i get the error from.
The unexpected display:
![image](https://github.com/catppuccin/nixos-search/assets/71222764/232adf55-e180-4054-8509-8cb93242c872)

**Comment by sydrinea** [comment]
Hey! It would be helpful if you could provide more specific reproduction steps (i.e. which browser are you using?). I've tried that query (Arc `0.107.0` w/Chromium `114.0.5735.106`) and everything seems to display normally on my end:
![Normal 404 Display](https://github.com/catppuccin/nixos-search/assets/68250402/e56b9aab-c9cf-4a24-afc2-1bf50de0c689)

**Comment by isabelroses** [comment]
The error has gone for me so I'm unsure what to do here.

**Comment by sydrinea** [comment]
I'll just close this issue in that case, feel free to reopen if it appears again and can be reproduced
